import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            padding: "16px",
            backgroundColor: "#222",
            color: "#fff",
            textAlign: "center",
          }}
        >
          <h1>My Website Header</h1>
        </header>
        <main style={{ minHeight: "80vh", padding: "20px" }}>{children}</main>
        <footer
          style={{
            padding: "12px",
            backgroundColor: "#f1f1f1",
            textAlign: "center",
          }}
        >
          <p>© 2025 My Website. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
